$kind: http-request
name: http://localhost:3000/api/applications
description: ""
url: http://localhost:3000/api/applications
method: POST
body:
  type: json
  content: "{\r

    \  \"opportunityId\": \"6a95db395c238e8f0cc44451\",\r

    \  \"coverLetter\": \"I am interested in this opportunity and believe my skills are a good match.\"\r

    }"
auth:
  type: bearer
  credentials:
    token: "{{supabase_service_role_api_key_1dmy}}"
order: 4503517030650049
